image: maven:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - /build

build:
  stage: build
  only:
    - master
  script:
    - echo "BUILDING PROJECT"
    - mvn clean compile


test:
  stage: test
  only:
    - master
  script:
    - echo "RUNNING TESTS"
    - mvn clean test -e



pages:
  needs: ["build"]
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - mkdir .public
    - cp -r /builds/eivisha/to-do-list/target/site/apidocs/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
