image: maven:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - /build

build:
  stage: build
  only:
    - testing
  script:
    - echo "BUILDING PROJECT"
    - mvn clean compile


test:
  stage: test
  only:
    - testing
  script:
    - echo "RUNNING TESTS"
    - mvn clean test -e



pages:
  stage: deploy
  script:
  - mvn javadoc:javadoc
  - mkdir .public
  - cp -r /target/site/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - testing

