image: maven:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - /root/.m2/repository/

build:
  stage: build
  only:
    - testing
  script:
    - echo "BUILDING PROJECT"
    - mvn clean compile


test:
  stage: test
  only:
    - testing
  script:
    - echo "RUNNING TESTS"
    - mvn clean test -e


  stage: deploy
  script:
  - mkdir .public
  - cp -r JavaDoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - testing

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r JavaDoc/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - testing

