image: maven:latest

stages:
  - build
  - test
  - deploy


cache:
  paths:
    - /build

build:
  stage: build
  only:
    - master
  script:
    - echo "BUILDING PROJECT"
    - mvn clean compile
  only: 
    - web 


test:
  stage: test
  only:
    - master
  script:
    - echo "RUNNING TESTS"
    - mvn clean test -e
  only: 
    - web 



pages:
  needs: ["build"]
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - mkdir .public
    - cp -r /builds/eivisha/to-do-list/target/site/apidocs/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - web


generatepdf:
   # vi kjører dette i en docker container, som kjører Ubuntu Linux
  stage: deploy
   # vi kjører den parallelt med å publisere javadoc til Pages
  script:
    
    - git clone https://gitlab.stud.iie.ntnu.no/eivisha/to-do-list.wiki.git  
    # hver eneste gitlab-wiki ligger i et eget repo, og kan klones med git som man kloner andre prosjekter
    - gwtc to-do-list.wiki  
    # Dette er kommandoen for å generere en singel HTML-fil av hele wikien
    - wkhtmltopdf documentation.html wiki.pdf 
     # Dette konverterer fra HTML til PDF
  artifacts:
    paths:
     - wiki.pdf 
      # Vi gjør fila tilgjengelig som en nedlastbar artefakt (CI/CD -> Pipelines, deretter ikon helt til høyre for bygget). Fila kalles wiki.pdf.
  only: 
    - web 
     # Only web gjør at vi kun kjører denne delen av pipeline når en trykker på knappen "Run pipeline"

